### ISSUE TITLE
大神，给个国内模型下载地址呀

### ISSUE THREAD

**Issue by zkvvv** [BlinkDL/AI-Writer#1]
RT

**Comment by BlinkDL** [comment]
请加 QQ 群 143626394 然后在群文件可以下载

**Comment by wanghaisheng** [comment]
这个gdriver的链接权限有问题吧  不会显示下载按钮 详细信息里提示Viewers cannot download
@BlinkDL

**Comment by BitFrank** [comment]
> 这个gdriver的链接权限有问题吧 不会显示下载按钮 详细信息里提示Viewers cannot download @BlinkDL
加 QQ 群吧

**Comment by BlinkDL** [comment]
已经模型上传到 Release 了
