### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by PoTaTo625** [BlinkDL/AI-Writer#10]
File "./run.py", line 103, in <module>
    w = w[:, :-TT].reshape(-1, TT, 2 * TT - 1)
RuntimeError: shape '[-1, 250, 499]' is invalid for input of size 2283000

个人感觉是参数问题（正确的废话）
好像……太大了？
可是我不敢乱动

**Comment by BlinkDL** [comment]
是自己训练的模型吗，运行需要对齐模型参数

**Comment by PoTaTo625** [comment]
不是
（已经解决，谢谢你）
