### ISSUE TITLE
release里的模型文件限定显卡类型的么

### ISSUE THREAD

**Issue by learningpro** [BlinkDL/AI-Writer#2]
看到release的模型文件后边都有标注是N卡还是A卡，意思是只能用指定的卡来跑么，请问有没有通用的模型，以及如何自己训练呢，多谢

**Comment by BlinkDL** [comment]
N卡模型：适合run.py的gpu模式，速度最快。另外run.py的cpu模式也用这个模型。

A/I卡模型：适合run.py的dml模式，其实任何显卡都可以跑，但是慢一些。

训练方法：https://github.com/BlinkDL/RWKV-LM/
可以加技术和用户 QQ 群 143626394（加入时请简单自我介绍）
