### ISSUE TITLE
第一次运行错误

### ISSUE THREAD

**Issue by MrQLEO** [BlinkDL/AI-Writer#9]
您好，我是一名python小白。
我按照您的说明运行run.py，但是报错“NO_SUCHFILE : Load model from model/wangwen-2022-02-15.onnx failed:Load model model/wangwen-2022-02-15.onnx failed. File doesn't exist”请问我该怎么生成wangwen-2022-02-15.onnx

**Comment by BlinkDL** [comment]
是A卡？下载 https://github.com/BlinkDL/AI-Writer/releases

**Comment by MrQLEO** [comment]
好的，多谢
